server:
  port: 8285

# SERVICE_REGISTRY ----------------------------------------------------------------------------------------------------
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}@${random.int}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka}

spring:
  application:
    name: notification-service
  messages:
    basename: messages
    use-code-as-default-message: true
    sleuth:
      messaging:
        kafka:
          enabled: true
          streams:
            enabled: true

# SMTP MAIL
smtp:
  username-smtp: ${USERNAME:vuongtien.dina@gmail.com}
  password-smtp: ${PASSWORD:sqxcdwfetwyedyod}
  host-smtp: ${HOST:smtp.gmail.com}
  port-smtp: ${POST:465}

mail:
  setting:
    constant:
      mail-from: ${MAIL_FROM:no-reply@tiendeptrai1234.com}

# FireBase
firebase:
  googleCredentials: firebase-service-account.json

# KAFKA ----------------------------------------------------------------------------------------------------
kafka:
  servers-config: ${KAFKA_SEVERS_CONFIG:localhost:29092,localhost:39093}
  notification-group: notification
  notification-topic: notification
  email-group: email
  email-topic: email
